// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ChannelConfig { id: string, name: string, filters: string[], match_description: boolean, outpath: string, picture_url: string | null, }