// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notification } from "./Notification";
import type { RecordingStatus } from "./RecordingStatus";
import type { Task } from "./Task";

export type Message = { ToRecord: Task } | { ToNotify: Notification } | { RecordingStatus: RecordingStatus };