// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotifierDiscordConfig } from "./NotifierDiscordConfig";

export interface NotifierConfig { discord: NotifierDiscordConfig | null, }