// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskStatus } from "./TaskStatus";

export interface NotifierDiscordConfig { webhook_url: string, notify_on: Array<TaskStatus>, }