// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Task } from "./Task";
import type { YTAStatus } from "./YTAStatus";

export interface RecordingStatus { task: Task, status: YTAStatus, }