// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Task { title: string, video_id: string, video_picture: string, channel_name: string, channel_id: string, channel_picture: string | null, output_directory: string, }