// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface WebserverConfig { bind_address: string | null, unix_path: string | null, }