// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface YtarchiveConfig { executable_path: string, working_directory: string, args: Array<string>, quality: string, delay_start: string, }