// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { YTAState } from "./YTAState";

export interface YTAStatus { version: string | null, state: YTAState, last_output: string | null, last_update: string, video_fragments: number | null, audio_fragments: number | null, total_size: string | null, video_quality: string | null, output_file: string | null, }